w3c/wcag-act-rules

_includes/testcase.html
css/main.scss

Fix for issue:
https://github.com/w3c/wcag-act/issues/187
DOM & Changes look like so:

fix: examples for accessibility [issue-187]

---

content/html-page-has-title-2779a5.md
content/image-button-accessible-name-59796f.md
content/index.md

As agreed proposed by the ACT Task force. This still needs to go into a CFC.

add new rule Image button has accessible name

---

content/html-page-has-title-2779a5.md
content/html-page-lang-b5c3f8.md
content/html-page-lang-valid-bf051a.md
content/html-page-lang-xml-lang-match-5b7ae0.md
content/image-button-accessible-name-59796f.md

As requested by the ACT Task Force:
- Added reference to ACT-Rules CG
- Added reference to EU and WAI-Tools

Refine rule acknowledgment

---

content/html-page-lang-valid-bf051a.md

PR update as documented in issue https://github.com/w3c/wcag-act/issues/429

Update HTML page lang attribute has valid language tag

---

wcag-mapping.json

This adds a JSON file which should allow for a mapping between WCAG resources and ACT rules.

Add JSON mapping between ACT and WCAG

---

content/implementations/23a2a8.md
content/implementations/2779a5.md
content/implementations/59796f.md
content/implementations/6cfa84.md
content/implementations/7d6734.md
content/implementations/b4f0c3.md
content/implementations/b5c3f8.md
content/implementations/bf051a.md
content/implementations/c487ae.md
content/implementations/e086e5.md

Made more than a few mistakes creating these tables. Looking forward to when this is automated.

Fix incorrect implementation links

---

content/about.md

+PLUS more explicit pointer to WCAG 2 Documents

missing period and a few tweaks

---

_data/wcag-act-rules/rule-versions.yml
_layouts/act_rule.html

- Do not show proposed rules if the approved rule is the same as the proposed rule
- Add "Previous version" text to older rule versions for consistency and clarity

Tweak Rule Version sections

---

.github/workflows/copy-rules-to-wcag.yml
.github/workflows/pr-to-publish.yml

I think the permissions on the repo need to be updated for this to work. They are under `Actions > General > Workflow permissions`

Automate publication PRs

---

_data/wcag-act-rules/implementations/alfa.json
_data/wcag-act-rules/implementations/axe-core.json
_data/wcag-act-rules/implementations/axe-devtools-pro.json
_data/wcag-act-rules/implementations/equal-access.json
_data/wcag-act-rules/implementations/qualweb.json
_data/wcag-act-rules/implementations/sortsite.json
_data/wcag-act-rules/implementations/trusted-tester.json
content-assets/wcag-act-rules/earl/axe-core.json
content-assets/wcag-act-rules/earl/axe-devtools-pro.json
content-assets/wcag-act-rules/earl/equal-access.json
content-assets/wcag-act-rules/earl/qualweb.json
content-assets/wcag-act-rules/earl/sortsite.json
content-assets/wcag-act-rules/testcases.json
content-assets/wcag-act-rules/testcases/8fc3b6/1b172036f8e219ef9b6f591d7f5df26e4ba11327.html
content-assets/wcag-act-rules/testcases/e88epe/ebd0080bacb8debc7ad069072240657df38c3e2c.html
content-assets/wcag-act-rules/testcases/qt1vmo/2a66c7b8d8ef78d350b1c995e0ad232008f6564f.html
content-assets/wcag-act-rules/testcases/qt1vmo/2e1787fbc8a76fd8a2f8cae08d72097dab75abfd.html
content-assets/wcag-act-rules/testcases/qt1vmo/485f10faf222cd48fea2ab3ee79c2d354e51ea33.html
content-assets/wcag-act-rules/testcases/qt1vmo/af4423575333947073fa3729f502ff0a0c6c2fbf.html
content-assets/wcag-act-rules/testcases/qt1vmo/bac67a5a2ada971100bbec89961ad3e6c869f268.html
content/rules/0va7u6/proposed.md
content/rules/8fc3b6/proposed.md
content/rules/e88epe/proposed.md
content/rules/qt1vmo/proposed.md
package-lock.json

* Add logo to accessible name of images where relevant

WAI website update, 2022/09/29

---

content/implementations.md

Fix markdown

---

_data/wcag-act-rules/act-implementations.yml

I'm working on updating the implementation report with this version.

Update Alfa version

---

_data/wcag-act-rules/act-implementations.yml
_data/wcag-act-rules/implementations/alfa.json
_data/wcag-act-rules/implementations/axe-core.json
_data/wcag-act-rules/implementations/axe-devtools-pro.json
_data/wcag-act-rules/implementations/ember-template-lint.json
_data/wcag-act-rules/implementations/equal-access.json
_data/wcag-act-rules/implementations/qualweb.json
_data/wcag-act-rules/implementations/sortsite.json
_layouts/act_implementation.html
_layouts/act_rule.html
content-assets/wcag-act-rules/act-styles.css
content-assets/wcag-act-rules/earl/alfa.json
content-assets/wcag-act-rules/earl/axe-core.json
content-assets/wcag-act-rules/earl/axe-devtools-pro.json
content-assets/wcag-act-rules/earl/sortsite.json
content-assets/wcag-act-rules/testcases.json
content-assets/wcag-act-rules/testcases/ff89c9/2ffe7d6cfa547dc8b107922a6bd7542ea36c96d6.html
content/_implementations-table.html
content/rules/ff89c9/proposed.md

- Updated implementation results
- UI fix for tables that would overflow the page width. They're now scrollable instead. (#165)

Publication December 5th 2022

---

_data/wcag-act-rules/implementations/alfa.json
_data/wcag-act-rules/implementations/axe-core.json
_data/wcag-act-rules/implementations/axe-devtools-pro.json
_data/wcag-act-rules/implementations/equal-access.json
_data/wcag-act-rules/implementations/qualweb.json
_data/wcag-act-rules/implementations/sortsite.json
content-assets/wcag-act-rules/earl/axe-core.json
content-assets/wcag-act-rules/earl/axe-devtools-pro.json
content-assets/wcag-act-rules/earl/qualweb.json
content-assets/wcag-act-rules/testcases.json
content-assets/wcag-act-rules/testcases/a25f45/17e68991f57cd20cd5c9fcf564d5a23ebb08c0f0.html
content/rules/a25f45/proposed.md
package-lock.json

Nothing special, 1 rule update and some corresponding implementations changes.

Publication December 8th, 2022

---

_layouts/act_rule.html
content/index.md

Create separate list for deprecated rules

---

_data/wcag-act-rules/act-implementations.yml
_data/wcag-act-rules/implementations/alfa-assisted.json
_data/wcag-act-rules/implementations/alfa.json
content-assets/wcag-act-rules/earl/alfa-assisted.json
content/implementations/alfa-assisted.md
content/implementations/alfa.md

Add Alfa semi-automated implementation

---

_data/wcag-act-rules/implementations/alfa-assisted.json
_data/wcag-act-rules/implementations/axe-core.json
_data/wcag-act-rules/implementations/axe-devtools-pro.json
_data/wcag-act-rules/implementations/qualweb.json
_data/wcag-act-rules/implementations/total-validator-browser.json
_data/wcag-act-rules/implementations/total-validator.json
_data/wcag-act-rules/implementations/trusted-tester.json
content-assets/wcag-act-rules/earl/alfa-assisted.json
content-assets/wcag-act-rules/earl/axe-core.json
content-assets/wcag-act-rules/earl/axe-devtools-pro.json
content-assets/wcag-act-rules/earl/qualweb.json
content-assets/wcag-act-rules/earl/total-validator-browser.json
content-assets/wcag-act-rules/earl/total-validator.json
content-assets/wcag-act-rules/earl/trusted-tester.json

Just updated implementation results

Publication 2023-05-09

---

.github/workflows/copy-to-evaluation-tools-list.yml

This PR pushes ACT implementation data to the wai-evaluation-tools-list repo every Monday.

Weekly sync with eval tool list master branch

---

_data/wcag-act-rules/implementations/alfa-assisted.json
_data/wcag-act-rules/implementations/alfa.json
_data/wcag-act-rules/implementations/axe-core.json
_data/wcag-act-rules/implementations/axe-devtools-pro.json
_data/wcag-act-rules/implementations/ember-template-lint.json
_data/wcag-act-rules/implementations/equal-access.json
_data/wcag-act-rules/implementations/qualweb.json
_data/wcag-act-rules/implementations/sortsite.json
_data/wcag-act-rules/implementations/total-validator-browser.json
_data/wcag-act-rules/implementations/total-validator.json
content-assets/wcag-act-rules/earl/axe-core.json
content-assets/wcag-act-rules/earl/axe-devtools-pro.json
content-assets/wcag-act-rules/earl/equal-access.json
content-assets/wcag-act-rules/earl/qualweb.json
content-assets/wcag-act-rules/testcases.json
content-assets/wcag-act-rules/testcases/5f99a7/830f50dcf51acb0b97b948000d7c163e50858312.html
content/rules/5f99a7/proposed.md

Sorry for the delay. Was off yesterday @shawna-slh

Publication 2023-05-25

---

_data/wcag-act-rules/implementations/alfa-assisted.json
_data/wcag-act-rules/implementations/alfa.json
_data/wcag-act-rules/implementations/axe-core.json
_data/wcag-act-rules/implementations/axe-devtools-pro.json
_data/wcag-act-rules/implementations/equal-access.json
_data/wcag-act-rules/implementations/qualweb.json
_data/wcag-act-rules/implementations/total-validator-browser.json
_data/wcag-act-rules/implementations/total-validator.json
content-assets/wcag-act-rules/earl/alfa-assisted.json
content-assets/wcag-act-rules/earl/alfa.json
content-assets/wcag-act-rules/earl/axe-core.json
content-assets/wcag-act-rules/earl/axe-devtools-pro.json
content-assets/wcag-act-rules/earl/equal-access.json
content-assets/wcag-act-rules/earl/qualweb.json
content-assets/wcag-act-rules/earl/total-validator-browser.json
content-assets/wcag-act-rules/earl/total-validator.json

Publication 2022/06/06

---

content/rules/24afc2/2022-06-23.md
content/rules/46ca7f/2022-01-28.md
content/rules/78fd32/2022-10-25.md
content/rules/9e45ec/2022-01-28.md
content/rules/9e45ec/2022-06-23.md
content/rules/akn7bn/2023-08-30.md
content/rules/de46e4/2022-06-23.md
content/rules/m6b1q3/2023-08-30.md

Fix issue caused by this oversight: https://github.com/act-rules/act-rules.github.io/pull/2153/files#r1439654599

Fix incorrect permalinks for recently added pages

---

_data/wcag-act-rules/act-implementations.yml

* Update standards to WCAG 2.2
* Update version number to current latest.

Update Alfa meta-data

---

.github/workflows/implementation-update.yml
_data/wcag-act-rules/act-implementations.yml
_data/wcag-act-rules/implementations/alfa-assisted.json
_data/wcag-act-rules/implementations/alfa.json
_data/wcag-act-rules/implementations/axe-core.json
_data/wcag-act-rules/implementations/axe-devtools-pro.json
_data/wcag-act-rules/implementations/equal-access.json
_data/wcag-act-rules/implementations/qualweb.json
_data/wcag-act-rules/implementations/sortsite.json
_data/wcag-act-rules/implementations/total-validator-browser.json
_data/wcag-act-rules/implementations/total-validator.json
content-assets/wcag-act-rules/earl/alfa-assisted.json
content-assets/wcag-act-rules/earl/alfa.json
content-assets/wcag-act-rules/earl/equal-access.json
content-assets/wcag-act-rules/earl/qualweb.json
content-assets/wcag-act-rules/earl/sortsite.json
content-assets/wcag-act-rules/earl/total-validator-browser.json
content-assets/wcag-act-rules/earl/total-validator.json
package-lock.json
package.json

This PR
* fixes a broken action by updating dependencies 
* updates implementation.

ACT-Rules Publication for Tuesday 4th June

---

.github/workflows/pr-to-publish.yml

From now on, Shawn will review and, when approved, Rémie will publish

Update publication workflow

---

_data/wcag-act-rules/rule-versions.yml
content-assets/wcag-act-rules/testcases.json
content/rules/b33eff/index.md
wcag-mapping.json

Here is a [preview of this rule](https://deploy-preview-335--wai-wcag-act-rules.netlify.app/standards-guidelines/act/rules/b33eff/).

Set Orientation of the page is not restricted using CSS transforms [b33eff] to approved
